### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by Ahnaf-codes**
Updated nextjs and other dependencies #26

### CODE REVIEW

**Comment by Ahnaf-codes** [comment]
@RuanAragao please review

**Comment by RuanAragao** [comment]
Worked to you?

**Comment by Ahnaf-codes** [comment]
> Worked to you?
yes

**Comment by Ahnaf-codes** [comment]
@RuanAragao please merge

**Comment by RuanAragao** [comment]
@Ahnaf-codes how to run? 

Here:

```bash
Shoppages on  Ahnaf-codes/master [!?] is 📦 v1.0.0 via ⬢ v18.18.0 using ☁️  default/ 
➜ yarn create-page
yarn run v1.22.19
warning package.json: No license field
$ node ./bin/index.js
/Users/ruanaragao/workspace/shopmaior/Shoppages/bin/index.js:5
const inquirer = require('inquirer');
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ruanaragao/workspace/shopmaior/Shoppages/node_modules/inquirer/lib/inquirer.js from /Users/ruanaragao/workspace/shopmaior/Shoppages/bin/index.js not supported.
Instead change the require of inquirer.js in /Users/ruanaragao/workspace/shopmaior/Shoppages/bin/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/ruanaragao/workspace/shopmaior/Shoppages/bin/index.js:5:18) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Pull request closed without merging**
